# Generated by Django 4.1 on 2022-09-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team', models.CharField(choices=[('Arsenal', 'Arsenal')], max_length=20)),
                ('Sum_Points_before', models.IntegerField()),
                ('Sum_Goal_For', models.IntegerField()),
                ('count_wining', models.IntegerField()),
                ('count_loose', models.IntegerField()),
                ('count_draw', models.IntegerField()),
                ('Goal_diff', models.IntegerField()),
                ('Loose', models.IntegerField()),
                ('A', models.IntegerField()),
                ('D', models.IntegerField()),
                ('H', models.IntegerField()),
            ],
        ),
    ]
