# Generated by Django 4.1 on 2022-09-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeployAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='Goal_diff',
            new_name='Goaldiff',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='Sum_Goal_For',
            new_name='SumGoalfor',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='Sum_Points_before',
            new_name='SumPointbefore',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='count_draw',
            new_name='countdraw',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='count_loose',
            new_name='countloose',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='count_wining',
            new_name='countwining',
        ),
    ]
