# Generated by Django 4.1 on 2022-09-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeployAPI', '0002_rename_goal_diff_team_goaldiff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team', models.CharField(choices=[('Arsenal', 'Arsenal')], max_length=20)),
                ('SumPointBefore', models.IntegerField()),
                ('SumGoalFor', models.IntegerField()),
                ('SumGoalAgainst', models.IntegerField()),
                ('countWining', models.IntegerField()),
                ('countLoose', models.IntegerField()),
                ('countDraw', models.IntegerField()),
                ('GoalDiff', models.IntegerField()),
                ('Draw', models.IntegerField()),
                ('Loose', models.IntegerField()),
                ('A', models.IntegerField()),
                ('D', models.IntegerField()),
                ('H', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
