# Generated by Django 4.1 on 2022-09-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeployAPI', '0003_teams_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teamset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HomeGoals', models.IntegerField()),
                ('AwayGoals', models.IntegerField()),
                ('SumPointBefore', models.IntegerField()),
                ('SumGoalFor', models.IntegerField()),
                ('SumGoalAgainst', models.IntegerField()),
                ('countWining', models.IntegerField()),
                ('countLoose', models.IntegerField()),
                ('countDraw', models.IntegerField()),
                ('GoalDiff', models.IntegerField()),
                ('Draw', models.IntegerField()),
                ('Loose', models.IntegerField()),
                ('A', models.IntegerField()),
                ('D', models.IntegerField()),
                ('H', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
