# Generated by Django 4.1 on 2022-09-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeployAPI', '0004_teamset_delete_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GamesPlayed', models.IntegerField()),
                ('SumPointBefore', models.IntegerField()),
                ('SumGoalFor', models.IntegerField()),
                ('SumGoalAgainst', models.IntegerField()),
                ('countWining', models.IntegerField()),
                ('countLoose', models.IntegerField()),
                ('countDraw', models.IntegerField()),
                ('GoalDiff', models.IntegerField()),
                ('Draw', models.IntegerField()),
                ('Loose', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Teamset',
        ),
    ]
