# Generated by Django 4.1 on 2022-09-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeployAPI', '0005_teams_delete_teamset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teamset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GamesPlayed', models.IntegerField()),
                ('SumPointBefore', models.IntegerField()),
                ('SumGoalFor', models.IntegerField()),
                ('SumGoalAgainst', models.IntegerField()),
                ('countWining', models.IntegerField()),
                ('countLoose', models.IntegerField()),
                ('countDraw', models.IntegerField()),
                ('GoalDiff', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
